name: CheckJS

on:
  # Run on pushes to select branches and on all pull requests.
  push:
    branches:
      - master
      - develop
      - 'release/[0-9]+.[0-9]+*'
      - 'hotfix/[0-9]+.[0-9]+*'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  grunt:
    runs-on: ubuntu-latest

    name: "CheckJS"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # The ubuntu images come with Node, npm and yarn pre-installed.
      # For Ubuntu 20, this means Node 14 will be used.
      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

      # Using this action to handle the caching of the Yarn dependencies.
      # https://github.com/actions/setup-node
      - name: Set up node to cache dependencies
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - name: Yarn install
        run: yarn install

      - name: Show debug info
        run: |
          npm --version
          node --version
          yarn --version
          grunt --version

      - name: Run Grunt tasks
        run: grunt check
